name: Finder
description: "Finding similar papers"
inputs:
  pdf_path:
    description: The path to the paper PDF file
    required: true
  openai_api_key:
    description: The OpenAI API key required to create new embeddings
    required: true
  issue_title:
    description: The title of the issue (used to check if this should run or not)
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'pip' # caching pip dependencies
    - name: Install dependencies
      shell: bash
      working-directory: ${{ github.action_path }}
      run: pip install -r ${{ github.action_path }}/requirements.txt
    - name: Find similar papers
      id: similar-papers-finder
      if: contains(${{ inputs.issue_title }}, 'PRE REVIEW')
      shell: bash
      working-directory: ${{ github.action_path }}
      run: |
        python ${{ github.action_path }}/find-similar-papers.py
branding:
  icon: upload
  color: green
