name: Finder
description: "Finding similar papers"
inputs:
  pdf_path:
    description: The path to the paper PDF file
    required: true
  openai_api_key:
    description: The OpenAI API key required to create new embeddings
    required: true
outputs:
  recommendations:
    description: "Output message with most similar paper recommendations"
    value: ${{ steps.similar-papers-finder.outputs.recommendations }}
runs:
  using: "composite"
  steps:
    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        # cache: 'pip' # caching pip dependencies
    - name: Install dependencies
      shell: bash
      working-directory: ${{ github.action_path }}
      run: pip install numpy openai==0.27.4 pandas requests scikit-learn scipy tqdm PyPDF2==1.26.0 matplotlib plotly
    - name: Find similar papers
      id: similar-papers-finder
      shell: bash
      # working-directory: ${{ github.action_path }}
      env:
        PDF_PATH: ${{ inputs.pdf_path }}
      run: |
        python ${{ github.action_path }}/find-similar-papers.py
branding:
  icon: upload
  color: green
